const Pages = {
  homePage: '/',
  discover: '/discover',
  bookings: '/bookings',
  hostPeople: '/hostpeople',
  onBoarding: '/on-boarding',
  signin: '/signin',
  hostSignIn: '/host/signin',
  signup: '/signup',
  hostSignUp: '/host/signup',
  guestInfo: '/info',
  hostInfo: '/host/info',
  hostDetails: '/host/details',
  verification: '/verification',
  hostVerification: '/host/verification',
  hostCreated: '/host-created',
  guestCreated: '/guest-created',
  forgotPassword: '/forget-password',
  resetPassword: '/reset-password',
  resetCreated: '/reset-created',
  event: '/event',
  faq: '/faq',
  privacyPolicy: '/privacy&policy',
  eventsLocation: '/events-location',
  guestDashboard: '/dashboard',
  hostDashboard: '/dashboard/host',
  hostDashboardSettings: '/dashboard/host/settings',
  hostDashboardSettingsPassword: '/dashboard/host/settings/change-password',
  hostDashboardEvents: '/dashboard/host/events',
  hostDashboardEventListing: '/dashboard/host/events/event-listings',
  hostDashboardEditEvents: '/dashboard/host/events/edit',
  hostDashboardBookings: '/dashboard/host/bookings',
  hostDashboardWallet: '/dashboard/host/wallet',
  hostDashboardAnalytics: '/dashboard/host/analytics',
  hostDashboardRatings: '/dashboard/host/ratings',
  hostDashboardBuyerProfie: '/dashboard/host/buyer-profile',
  hostDashboardEventPerformance: '/dashboard/host/event-performance',
  hostDashboardAudienceBehavour: '/dashboard/host/audience-behaviour',
  hostDashboardReviews: '/dashboard/host/reviews',
  hostDashboardEventPerformanceEvent: '/dashboard/host/event-performance/event',
};

export default Pages;
